# Generated by Django 4.2.7 on 2025-11-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('broker_api', 'Broker API'), ('csv_import', 'CSV Import'), ('manual', 'Manual Entry'), ('websocket', 'WebSocket Stream')], default='broker_api', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict, help_text='API keys, endpoints, etc. (encrypted in production)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(default='pending', max_length=20)),
                ('last_sync_message', models.TextField(blank=True)),
                ('total_candles_synced', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'marketdata_datasource',
            },
        ),
        migrations.CreateModel(
            name='OHLCVCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='Trading pair (e.g., EURUSD, GBPUSD, BTCUSD)', max_length=20)),
                ('timeframe', models.CharField(db_index=True, help_text='Candle timeframe (1m, 5m, 15m, 30m, 1h, 4h, 1d)', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Candle open time (UTC)')),
                ('open_price', models.DecimalField(decimal_places=8, help_text='Opening price', max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, help_text='Highest price during period', max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, help_text='Lowest price during period', max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, help_text='Closing price', max_digits=20)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Trading volume (may not be available for forex)', max_digits=20, null=True)),
                ('source', models.CharField(default='manual', help_text='Data source (broker API, CSV import, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OHLCV Candle',
                'verbose_name_plural': 'OHLCV Candles',
                'db_table': 'marketdata_ohlcv',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='marketdata__symbol_b8f6f4_idx'), models.Index(fields=['timestamp'], name='marketdata__timesta_317e84_idx')],
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
    ]
