# Generated by Django 4.2.7 on 2025-11-10 21:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(choices=[('ftmo', 'FTMO'), ('funding_pips', 'Funding Pips'), ('mff', 'MyForexFunds'), ('tft', 'The Funded Trader'), ('ftc', 'FundedNext'), ('e8', 'E8 Funding'), ('custom', 'Custom Template')], default='custom', max_length=50)),
                ('phase', models.CharField(choices=[('phase1', 'Phase 1 (Evaluation)'), ('phase2', 'Phase 2 (Verification)'), ('funded', 'Funded Account')], default='phase1', max_length=20)),
                ('template_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('account_size', models.DecimalField(decimal_places=2, default=100000, help_text='Starting account balance', max_digits=12)),
                ('profit_target_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Required profit % to pass', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_daily_drawdown_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Max daily loss %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_total_drawdown_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Max total loss %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('challenge_duration_days', models.IntegerField(default=30, help_text='Total days to complete challenge')),
                ('min_trading_days', models.IntegerField(default=5, help_text='Minimum days with trades required')),
                ('min_trade_duration_minutes', models.IntegerField(default=5, help_text='Minimum holding time per trade (0 = no limit)')),
                ('max_leverage', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum leverage allowed', max_digits=5)),
                ('allow_weekend_holding', models.BooleanField(default=False, help_text='Allow holding positions over weekend')),
                ('allow_news_trading', models.BooleanField(default=True, help_text='Allow trading during high-impact news')),
                ('max_position_size_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Max position size as % of account', max_digits=5)),
                ('custom_rules', models.JSONField(blank=True, default=dict, help_text='Additional firm-specific rules')),
                ('profit_split_percent', models.DecimalField(decimal_places=2, default=80.0, help_text="Trader's profit share %", max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firm Template',
                'verbose_name_plural': 'Firm Templates',
                'ordering': ['firm_name', 'phase'],
            },
        ),
        migrations.CreateModel(
            name='PropChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('failed', 'Failed'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peak_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('current_daily_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_daily_drawdown_reached', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_total_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_total_drawdown_reached', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('trading_days_count', models.IntegerField(default=0)),
                ('last_trade_date', models.DateField(blank=True, null=True)),
                ('violation_count', models.IntegerField(default=0)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('funding_readiness_score', models.DecimalField(decimal_places=2, default=50.0, help_text='AI-calculated readiness (0-100)', max_digits=5)),
                ('pass_probability', models.DecimalField(decimal_places=2, default=50.0, help_text='ML-predicted pass probability', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='propcoach.firmtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propcoach_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prop Challenge',
                'verbose_name_plural': 'Prop Challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position_size_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leverage_used', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_loss_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('hold_duration_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('strategy_used', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.IntegerField(default=50)),
                ('trader_sentiment', models.CharField(blank=True, max_length=50)),
                ('has_violations', models.BooleanField(default=False)),
                ('violation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='propcoach.propchallenge')),
            ],
            options={
                'verbose_name': 'Trade Record',
                'verbose_name_plural': 'Trade Records',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='PropTrainingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('challenges_attempted', models.IntegerField(default=0)),
                ('challenges_passed', models.IntegerField(default=0)),
                ('challenges_failed', models.IntegerField(default=0)),
                ('avg_win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_profit_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rule_violations_count', models.IntegerField(default=0)),
                ('discipline_improvement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('readiness_score', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('learning_insights', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='PropRuleViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('daily_drawdown', 'Daily Drawdown Exceeded'), ('total_drawdown', 'Total Drawdown Exceeded'), ('min_trade_time', 'Minimum Trade Duration Violated'), ('weekend_hold', 'Weekend Holding Violation'), ('news_trading', 'News Trading Violation'), ('max_leverage', 'Maximum Leverage Exceeded'), ('max_position_size', 'Position Size Too Large'), ('consistency', 'Inconsistent Position Sizing'), ('time_expired', 'Challenge Time Expired'), ('other', 'Other Violation')], max_length=50)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical - Challenge Failed')], default='minor', max_length=20)),
                ('description', models.TextField()),
                ('value_breached', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('limit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('auto_detected', models.BooleanField(default=True)),
                ('challenge_failed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='propcoach.propchallenge')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='propcoach.traderecord')),
            ],
            options={
                'verbose_name': 'Rule Violation',
                'verbose_name_plural': 'Rule Violations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CoachingFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('daily_summary', 'Daily Summary'), ('performance_alert', 'Performance Alert'), ('behavioral_insight', 'Behavioral Insight'), ('risk_warning', 'Risk Warning'), ('achievement', 'Achievement Unlocked'), ('strategy_suggestion', 'Strategy Suggestion')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('metrics_data', models.JSONField(blank=True, default=dict)),
                ('emotional_tone', models.CharField(blank=True, max_length=50)),
                ('detected_biases', models.JSONField(blank=True, default=list)),
                ('discipline_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_read', models.BooleanField(default=False)),
                ('is_actionable', models.BooleanField(default=True)),
                ('action_taken', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_feedback', to='propcoach.propchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coaching Feedback',
                'verbose_name_plural': 'Coaching Feedback',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='traderecord',
            index=models.Index(fields=['challenge', 'status'], name='propcoach_t_challen_21400c_idx'),
        ),
        migrations.AddIndex(
            model_name='traderecord',
            index=models.Index(fields=['entry_time'], name='propcoach_t_entry_t_cfc066_idx'),
        ),
        migrations.AddIndex(
            model_name='propruleviolation',
            index=models.Index(fields=['challenge', 'severity'], name='propcoach_p_challen_4605ef_idx'),
        ),
        migrations.AddIndex(
            model_name='propruleviolation',
            index=models.Index(fields=['violation_type', 'timestamp'], name='propcoach_p_violati_b88107_idx'),
        ),
        migrations.AddIndex(
            model_name='propchallenge',
            index=models.Index(fields=['user', 'status'], name='propcoach_p_user_id_5dee57_idx'),
        ),
        migrations.AddIndex(
            model_name='propchallenge',
            index=models.Index(fields=['status', 'start_date'], name='propcoach_p_status_7dbed3_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingfeedback',
            index=models.Index(fields=['user', 'is_read'], name='propcoach_c_user_id_ca6bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingfeedback',
            index=models.Index(fields=['challenge', 'timestamp'], name='propcoach_c_challen_34d356_idx'),
        ),
    ]
