# Generated by Django 4.2.7 on 2025-11-11 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KBSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_entries', models.IntegerField(default=0)),
                ('total_relationships', models.IntegerField(default=0)),
                ('total_sources', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text='What changed in this version')),
                ('snapshot_data', models.JSONField(default=dict, help_text='Compressed KB state')),
                ('backup_path', models.CharField(blank=True, help_text='Path to FAISS index backup', max_length=512)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'KB Snapshot',
                'verbose_name_plural': 'KB Snapshots',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField()),
                ('trust_level', models.CharField(choices=[('high', 'High - Authoritative (Investopedia, Official Docs)'), ('medium', 'Medium - Reputable (FXStreet, BabyPips)'), ('low', 'Low - Community/Blog'), ('blacklisted', 'Blacklisted')], default='medium', max_length=20)),
                ('respect_robots_txt', models.BooleanField(default=True)),
                ('rate_limit_seconds', models.IntegerField(default=2, help_text='Seconds between requests')),
                ('max_depth', models.IntegerField(default=3, help_text='Max crawl depth from seed URLs')),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('total_entries', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Legal notes, TOS constraints, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Source',
                'verbose_name_plural': 'Knowledge Sources',
                'ordering': ['-trust_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(db_index=True, max_length=512)),
                ('query_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('results', models.JSONField(help_text='Top-K KB entry IDs + scores')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=20)),
                ('concept_tags', models.JSONField(default=list, help_text='Related concepts for invalidation')),
            ],
            options={
                'verbose_name': 'Query Cache',
                'verbose_name_plural': 'Query Cache',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['expires_at', 'symbol'], name='knowledge_b_expires_ab0fff_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, help_text="Canonical term (e.g., 'Order Block')", max_length=255)),
                ('aliases', models.JSONField(default=list, help_text="Alternative names (e.g., ['OB', 'demand zone'])")),
                ('summary', models.TextField(help_text='One-liner definition (1-2 sentences)')),
                ('definition', models.TextField(help_text='Detailed explanation (3-5 paragraphs)')),
                ('examples', models.TextField(blank=True, help_text='Usage examples and scenarios')),
                ('category', models.CharField(choices=[('smc', 'Smart Money Concepts'), ('ict', 'Inner Circle Trader'), ('ta', 'Technical Analysis'), ('risk', 'Risk Management'), ('psychology', 'Trading Psychology'), ('fundamentals', 'Fundamental Analysis'), ('orderflow', 'Order Flow'), ('market_structure', 'Market Structure'), ('liquidity', 'Liquidity Concepts'), ('other', 'Other')], db_index=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('intro', 'Introductory'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('asset_classes', models.JSONField(default=list, help_text='Applicable asset classes')),
                ('source_url', models.URLField(help_text='Original page URL')),
                ('crawl_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('license_info', models.CharField(blank=True, help_text='CC-BY, Fair Use, etc.', max_length=255)),
                ('embedding_summary', models.JSONField(blank=True, help_text='Vector for summary text', null=True)),
                ('embedding_full', models.JSONField(blank=True, help_text='Vector for full definition', null=True)),
                ('embedding_model', models.CharField(default='all-MiniLM-L6-v2', max_length=100)),
                ('quality_score', models.FloatField(db_index=True, default=0.5, help_text='0.0-1.0 quality rating')),
                ('relevance_score', models.FloatField(default=0.5, help_text='How relevant to trading')),
                ('completeness_score', models.FloatField(default=0.5, help_text='Has examples, definition, etc.')),
                ('view_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1, help_text='KB version for snapshot tracking')),
                ('is_verified', models.BooleanField(default=False, help_text='Human-reviewed and approved')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='knowledge_base.source')),
            ],
            options={
                'verbose_name': 'Knowledge Entry',
                'verbose_name_plural': 'Knowledge Entries',
                'ordering': ['-quality_score', 'term'],
            },
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], db_index=True, default='pending', max_length=20)),
                ('urls_discovered', models.IntegerField(default=0)),
                ('urls_crawled', models.IntegerField(default=0)),
                ('entries_created', models.IntegerField(default=0)),
                ('entries_updated', models.IntegerField(default=0)),
                ('entries_skipped', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('config_snapshot', models.JSONField(default=dict, help_text='Crawl parameters used')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_logs', to='knowledge_base.source')),
            ],
            options={
                'verbose_name': 'Crawl Log',
                'verbose_name_plural': 'Crawl Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('related_to', 'Related To'), ('is_subconcept_of', 'Is Subconcept Of'), ('prerequisite_for', 'Prerequisite For'), ('contraindicates', 'Contraindicates'), ('common_with', 'Commonly Occurs With'), ('alternative_to', 'Alternative To')], db_index=True, max_length=50)),
                ('strength', models.FloatField(default=1.0, help_text='Relationship strength (0.0-1.0)')),
                ('description', models.TextField(blank=True, help_text='Why these concepts are related')),
                ('is_auto_detected', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='knowledge_base.knowledgeentry')),
                ('target_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='knowledge_base.knowledgeentry')),
            ],
            options={
                'verbose_name': 'Concept Relationship',
                'verbose_name_plural': 'Concept Relationships',
                'ordering': ['-strength', 'relationship_type'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['category', 'quality_score'], name='knowledge_b_categor_b3919b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['term', 'is_active'], name='knowledge_b_term_038df2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptrelationship',
            unique_together={('source_concept', 'target_concept', 'relationship_type')},
        ),
    ]
