# Generated by Django 4.2.7 on 2025-11-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentry',
            name='common_pitfalls',
            field=models.JSONField(default=list, help_text='Common mistakes and misconceptions'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='market_behavior_patterns',
            field=models.JSONField(default=list, help_text='Observable price patterns for this concept'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='psychology_context',
            field=models.TextField(blank=True, help_text='Psychological aspects and trader behavior'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='related_concepts',
            field=models.JSONField(default=list, help_text='Related strategy concepts'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='trade_structures',
            field=models.JSONField(default=list, help_text='Key setups and entry/exit structures'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='visual_description',
            field=models.TextField(blank=True, help_text='Text-based chart pattern description'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='category',
            field=models.CharField(choices=[('smc', 'Smart Money Concepts'), ('ict', 'Inner Circle Trader'), ('trend', 'Trend-Following Systems'), ('breakout', 'Breakout Strategies'), ('mean_reversion', 'Mean Reversion Models'), ('squeeze', 'Squeeze Volatility Setups'), ('scalping', 'Scalping / Momentum Trading'), ('vwap', 'VWAP Reclaim Systems'), ('supply_demand', 'Supply & Demand Zone Analysis'), ('confluence', 'Multi-Timeframe Confluence'), ('ta', 'Technical Analysis'), ('risk', 'Risk Management'), ('psychology', 'Trading Psychology'), ('fundamentals', 'Fundamental Analysis'), ('orderflow', 'Order Flow'), ('market_structure', 'Market Structure'), ('liquidity', 'Liquidity Concepts'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
