# Generated by Django 4.2.7 on 2025-11-09 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(help_text='Trading strategy name', max_length=100)),
                ('symbol', models.CharField(blank=True, help_text='Symbol filter (blank = all)', max_length=20)),
                ('timeframe', models.CharField(blank=True, help_text='Timeframe filter', max_length=10)),
                ('start_date', models.DateField(help_text='Start date for backtest period')),
                ('end_date', models.DateField(help_text='End date for backtest period')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Additional parameters: min_score, ignore_news, etc.')),
                ('total_trades', models.IntegerField(default=0, help_text='Total number of trades in backtest')),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0, help_text='Win rate as percentage (0-100)')),
                ('avg_rr', models.FloatField(default=0.0, help_text='Average Risk/Reward ratio')),
                ('max_drawdown', models.FloatField(default=0.0, help_text='Maximum drawdown percentage')),
                ('profit_factor', models.FloatField(default=0.0, help_text='Profit factor (gross profit / gross loss)')),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, help_text='Total P&L in pips/points', max_digits=10)),
                ('equity_curve', models.JSONField(blank=True, default=list, help_text='List of equity values over time [{date, equity}, ...]')),
                ('trade_details', models.JSONField(blank=True, default=list, help_text='List of individual trade results for replay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_saved', models.BooleanField(default=False, help_text='User explicitly saved this backtest for future reference')),
                ('name', models.CharField(blank=True, help_text='Optional name for saved backtests', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_backtest_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_b_user_id_904adc_idx'), models.Index(fields=['strategy', 'symbol'], name='analytics_b_strateg_35ad13_idx')],
            },
        ),
    ]
