# Generated by Django 4.2.7 on 2025-11-09 20:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPerformanceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date for this performance snapshot')),
                ('total_signals', models.IntegerField(default=0)),
                ('allowed_signals', models.IntegerField(default=0)),
                ('rejected_signals', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('loss_count', models.IntegerField(default=0)),
                ('breakeven_count', models.IntegerField(default=0)),
                ('total_pips', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('avg_ai_score', models.FloatField(default=0.0)),
                ('best_strategy', models.CharField(blank=True, max_length=50)),
                ('best_session', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Performance Cache',
                'verbose_name_plural': 'Daily Performance Caches',
                'db_table': 'analytics_daily_performance_cache',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='daily_perf_user_date_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
