# Generated by Django 4.2.7 on 2025-11-10 18:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('keyword_list', models.TextField(help_text='Comma-separated keywords')),
                ('news_count', models.IntegerField(default=0, help_text='Number of related news items')),
                ('avg_sentiment', models.FloatField(default=0.0, help_text='Average sentiment of related news')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News Topic',
                'verbose_name_plural': 'News Topics',
                'ordering': ['-news_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, help_text='Trading symbol (e.g., EURUSD, XAUUSD)', max_length=20)),
                ('headline', models.TextField(help_text='News headline')),
                ('sentiment', models.FloatField(default=0.0, help_text='Sentiment score: -1.0 (negative) to 1.0 (positive)')),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Impact level based on content analysis', max_length=10)),
                ('topic', models.CharField(blank=True, help_text='Detected topic/category', max_length=100, null=True)),
                ('source', models.CharField(help_text='News source name', max_length=100)),
                ('source_url', models.URLField(blank=True, help_text='Original article URL', null=True)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA256 hash for deduplication', max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Publication timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News Event',
                'verbose_name_plural': 'News Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='zennews_new_symbol_6f4a0e_idx'), models.Index(fields=['impact_level', 'timestamp'], name='zennews_new_impact__ade490_idx'), models.Index(fields=['content_hash'], name='zennews_new_content_71ea97_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(default='high_impact', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='zennews.newsevent')),
            ],
            options={
                'verbose_name': 'News Alert',
                'verbose_name_plural': 'News Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
