# Generated by Django 4.2.7 on 2025-11-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zennews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='content_extract',
            field=models.TextField(blank=True, help_text='Brief content extract (25 words max)'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Alias for timestamp', null=True),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='relevance_rank',
            field=models.IntegerField(db_index=True, default=50, help_text='Relevance ranking 0-100 (higher = more relevant)'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='sentiment_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Alias for sentiment (backward compat)'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='symbol_tags',
            field=models.JSONField(default=list, help_text='List of related symbols [EURUSD, GBP, EUR]'),
        ),
    ]
