# Generated by Django 4.2.7 on 2025-11-09 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('admin_replied', 'Admin Replied'), ('user_replied', 'User Replied'), ('closed', 'Closed')], default='open', max_length=20)),
                ('signal_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_unread_user_message', models.BooleanField(default=False)),
                ('has_unread_admin_message', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_thread',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_admin_message', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportthread')),
            ],
            options={
                'db_table': 'support_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['user', 'status'], name='support_thr_user_id_7d9234_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['status', '-last_message_at'], name='support_thr_status_cf91c9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['thread', 'created_at'], name='support_mes_thread__8903ce_idx'),
        ),
    ]
