# Generated by Django 4.2.7 on 2025-11-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_webhookconfig_hmac_secret'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportthread',
            name='signal_id',
        ),
        migrations.AddField(
            model_name='supportthread',
            name='signal',
            field=models.ForeignKey(blank=True, help_text='Optionally attach a signal to this support thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_threads', to='signals.signal'),
        ),
    ]
