# Generated by Django 4.2.7 on 2025-11-10 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_id', models.IntegerField(db_index=True, help_text='ML-assigned cluster ID')),
                ('cluster_name', models.CharField(help_text="Human-readable cluster name (e.g., 'Morning Breakouts')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy_pattern', models.CharField(help_text='Dominant strategy pattern in this cluster', max_length=100)),
                ('typical_timeframe', models.CharField(max_length=10)),
                ('typical_symbols', models.JSONField(default=list, help_text='Common symbols in cluster')),
                ('signal_count', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.5)),
                ('avg_profit_factor', models.FloatField(default=1.0)),
                ('avg_risk_reward', models.FloatField(default=1.5)),
                ('sharpe_ratio', models.FloatField(default=0.0)),
                ('feature_centroid', models.JSONField(default=dict, help_text='Average feature vector for this cluster')),
                ('reliability_score', models.FloatField(default=0.5, help_text='Overall cluster reliability: 0 (unreliable) to 1 (highly reliable)')),
                ('confidence_interval', models.FloatField(default=0.95, help_text='Statistical confidence in performance metrics')),
                ('preferred_regimes', models.JSONField(default=list, help_text='Regimes where this cluster performs best')),
            ],
            options={
                'ordering': ['-reliability_score'],
                'indexes': [models.Index(fields=['cluster_id'], name='cognition_s_cluster_9e80c3_idx'), models.Index(fields=['reliability_score'], name='cognition_s_reliabi_f8b11f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketRegime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], default='15m', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('regime_type', models.CharField(choices=[('strong_trend', 'Strong Trend'), ('weak_trend', 'Weak Trend'), ('choppy', 'Choppy/Range-bound'), ('squeeze', 'Squeeze/Consolidation'), ('volatile', 'High Volatility'), ('quiet', 'Low Volatility')], db_index=True, max_length=20)),
                ('regime_confidence', models.FloatField(help_text='Confidence in regime classification: 0 to 1')),
                ('trend_strength', models.FloatField(help_text='ADX-based trend strength: 0 (no trend) to 1 (strong trend)')),
                ('volatility_percentile', models.FloatField(help_text='Current volatility vs 30-day range: 0 (low) to 1 (high)')),
                ('volume_profile', models.FloatField(help_text='Volume relative to average: 0 (low) to 2+ (high)')),
                ('detected_patterns', models.JSONField(default=list, help_text="Technical patterns detected (e.g., 'higher_highs', 'range_bound')")),
                ('feature_vector', models.JSONField(default=dict, help_text='Numerical features used for classification')),
                ('regime_bias', models.FloatField(default=0.0, help_text='Trading bias: -1 (avoid), 0 (neutral), +1 (favorable)')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='cognition_m_symbol_63a9f6_idx'), models.Index(fields=['regime_type'], name='cognition_m_regime__128c79_idx')],
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='TraderPsychology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('text_content', models.TextField(help_text='Journal entry, chat message, or feedback')),
                ('source_type', models.CharField(choices=[('journal', 'Trade Journal'), ('chat', 'Chat Message'), ('feedback', 'Feedback Form'), ('note', 'Personal Note')], default='journal', max_length=20)),
                ('sentiment_score', models.FloatField(help_text='Overall sentiment: -1 (very negative) to +1 (very positive)')),
                ('confidence_level', models.FloatField(help_text='Trader confidence: 0 (uncertain) to 1 (highly confident)')),
                ('emotional_tone', models.CharField(choices=[('fearful', 'Fearful'), ('anxious', 'Anxious'), ('neutral', 'Neutral'), ('confident', 'Confident'), ('overconfident', 'Overconfident'), ('greedy', 'Greedy'), ('disciplined', 'Disciplined')], max_length=20)),
                ('key_phrases', models.JSONField(default=list, help_text='Important phrases extracted')),
                ('entities', models.JSONField(default=dict, help_text='Named entities found (symbols, strategies)')),
                ('risk_tolerance', models.FloatField(default=0.5, help_text='Implied risk tolerance: 0 (risk-averse) to 1 (risk-seeking)')),
                ('patience_score', models.FloatField(default=0.5, help_text='Patience level: 0 (impulsive) to 1 (patient)')),
                ('discipline_score', models.FloatField(default=0.5, help_text='Discipline level: 0 (undisciplined) to 1 (highly disciplined)')),
                ('detected_biases', models.JSONField(default=list, help_text="List of cognitive biases detected (e.g., 'overconfidence', 'revenge_trading')")),
                ('bias_severity', models.FloatField(default=0.0, help_text='Overall bias severity: 0 (minimal) to 1 (severe)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychology_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trader Psychology Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='cognition_t_user_id_48071e_idx'), models.Index(fields=['emotional_tone'], name='cognition_t_emotion_3db5c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropFirmPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('challenge_type', models.CharField(choices=[('phase1', 'Phase 1 Challenge'), ('phase2', 'Phase 2 Challenge'), ('funded', 'Funded Account')], default='phase1', max_length=20)),
                ('account_size', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_remaining', models.IntegerField(default=30)),
                ('trades_taken', models.IntegerField(default=0)),
                ('current_win_rate', models.FloatField(default=0.5)),
                ('current_profit_factor', models.FloatField(default=1.0)),
                ('current_sharpe', models.FloatField(default=0.0)),
                ('avg_trade_duration', models.FloatField(default=0.0, help_text='Hours')),
                ('avg_confidence_score', models.FloatField(default=0.5)),
                ('avg_discipline_score', models.FloatField(default=0.5)),
                ('recent_bias_severity', models.FloatField(default=0.0)),
                ('pass_probability', models.FloatField(help_text='Predicted probability of passing challenge: 0 to 1')),
                ('estimated_completion_days', models.IntegerField(help_text='Estimated days to hit profit target')),
                ('risk_of_failure', models.FloatField(help_text='Probability of hitting max drawdown: 0 to 1')),
                ('recommended_adjustments', models.JSONField(default=list, help_text='Suggested changes to improve pass probability')),
                ('confidence_level', models.FloatField(default=0.7, help_text='Confidence in prediction: 0 to 1')),
                ('feature_vector', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='cognition_p_user_id_252d26_idx'), models.Index(fields=['pass_probability'], name='cognition_p_pass_pr_10382a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CognitionInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('insight_type', models.CharField(choices=[('daily_summary', 'Daily Summary'), ('psychology_alert', 'Psychology Alert'), ('regime_change', 'Regime Change'), ('cluster_insight', 'Cluster Insight'), ('prop_warning', 'Prop Firm Warning')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=20)),
                ('related_data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_actionable', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='cognition_c_user_id_02eb7f_idx'), models.Index(fields=['insight_type'], name='cognition_c_insight_6a2760_idx')],
            },
        ),
    ]
