# Generated by Django 4.2.7 on 2025-11-09 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_threshold', models.FloatField(default=60.0, help_text='Minimum similarity score for Q&A matching (0-100)')),
                ('enable_user_stats', models.BooleanField(default=True, help_text='Allow bot to query user-specific data')),
                ('enable_signal_queries', models.BooleanField(default=True, help_text='Allow bot to query signal database')),
                ('enable_learning', models.BooleanField(default=False, help_text='Enable bot to learn from conversations (future feature)')),
                ('default_fallback_message', models.TextField(default="I'm not sure about that. Could you rephrase your question or ask about strategies, signals, risk management, or your challenge status?", help_text='Response when no match is found')),
                ('max_conversation_history', models.IntegerField(default=100, help_text='Maximum conversation records per user')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Settings',
                'verbose_name_plural': 'Bot Settings',
                'db_table': 'bot_settings',
            },
        ),
        migrations.CreateModel(
            name='BotQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question or query phrase (supports multiple variations separated by |)')),
                ('answer', models.TextField(help_text='Bot response to this question')),
                ('category', models.CharField(choices=[('general', 'General'), ('strategy', 'Trading Strategy'), ('risk', 'Risk Management'), ('challenge', 'Prop Challenge'), ('technical', 'Technical Support'), ('signals', 'Signal Information'), ('journal', 'Trade Journal'), ('replay', 'Trade Replay')], db_index=True, default='general', max_length=20)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for better matching', max_length=500)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority answers shown first (0-100)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this answer was used')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_qas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Q&A',
                'verbose_name_plural': 'Bot Q&As',
                'db_table': 'bot_qa',
                'ordering': ['-priority', '-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Browser session identifier', max_length=100)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0, help_text='Match confidence (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_qa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='bot.botqa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Conversation',
                'verbose_name_plural': 'Bot Conversations',
                'db_table': 'bot_conversation',
                'ordering': ['-created_at'],
            },
        ),
    ]
