# Generated by Django 4.2.7 on 2025-11-09 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text="User's input/query")),
                ('response', models.TextField(help_text="Bot's response")),
                ('is_command', models.BooleanField(default=False, help_text='True if prompt was a slash command')),
                ('command_type', models.CharField(blank=True, help_text='Command type: score, prop, strategy, etc.', max_length=50)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Time taken to generate response (milliseconds)', null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Match confidence if using Q&A system')),
                ('session_id', models.CharField(blank=True, help_text='Browser session identifier for conversation threading', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('matched_qa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_history', to='bot.botqa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Chat History',
                'verbose_name_plural': 'Bot Chat Histories',
                'db_table': 'bot_chat_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='bot_chat_hi_user_id_91a6bd_idx'), models.Index(fields=['is_command', 'command_type'], name='bot_chat_hi_is_comm_091d4c_idx')],
            },
        ),
    ]
