# Generated by Django 4.2.7 on 2025-11-13 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autopsy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Bar timestamp')),
                ('regime', models.CharField(choices=[('trending', 'Trending'), ('ranging', 'Ranging'), ('volatile', 'Volatile'), ('consolidation', 'Consolidation'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('structure', models.CharField(choices=[('bos', 'Break of Structure'), ('choch', 'Change of Character'), ('pullback', 'Pullback'), ('liquidity_sweep', 'Liquidity Sweep'), ('fvg', 'Fair Value Gap'), ('order_block', 'Order Block'), ('eqh', 'Equal Highs'), ('eql', 'Equal Lows'), ('compression', 'Compression'), ('none', 'No Clear Structure')], default='none', max_length=30)),
                ('momentum', models.CharField(choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('diverging', 'Diverging'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('volume_state', models.CharField(choices=[('spike', 'Volume Spike'), ('drop', 'Volume Drop'), ('normal', 'Normal Volume')], default='normal', max_length=20)),
                ('session', models.CharField(choices=[('london', 'London'), ('newyork', 'New York'), ('asia', 'Asia'), ('off', 'Off-Session')], default='off', max_length=20)),
                ('expected_behavior', models.CharField(blank=True, help_text='Expansion | Retracement | Reversal | Liquidity grab', max_length=100)),
                ('strength', models.IntegerField(default=0, help_text='0-100 strength score')),
                ('risk_notes', models.JSONField(default=list, help_text='Array of risk warnings')),
                ('insight_text', models.TextField(help_text='Natural language market analysis')),
                ('suggestion', models.TextField(blank=True, help_text='Actionable guidance (not buy/sell)')),
                ('insight_index', models.IntegerField(default=0, help_text='0-100 insight quality score')),
                ('structure_clarity', models.IntegerField(default=0, help_text='0-100')),
                ('regime_stability', models.IntegerField(default=0, help_text='0-100')),
                ('volume_quality', models.IntegerField(default=0, help_text='0-100')),
                ('momentum_alignment', models.IntegerField(default=0, help_text='0-100')),
                ('session_validity', models.IntegerField(default=0, help_text='0-100')),
                ('risk_level', models.IntegerField(default=0, help_text='0-100, higher = more risk')),
                ('news_impact', models.CharField(blank=True, help_text='high | medium | low | none', max_length=20)),
                ('news_context', models.TextField(blank=True, help_text='High-impact USD news in 27 minutes')),
                ('chart_labels', models.JSONField(default=dict, help_text="{'structure': 'BOS', 'regime': 'Trending', ...}")),
                ('vocabulary_hash', models.CharField(blank=True, db_index=True, help_text='Hash of word choices to ensure uniqueness', max_length=64)),
                ('sentence_structure_id', models.CharField(blank=True, help_text='Template ID used for variation', max_length=50)),
                ('raw_metadata', models.JSONField(default=dict, help_text='Complete Pine Script output')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Market Insight',
                'verbose_name_plural': 'Market Insights',
                'db_table': 'autopsy_marketinsight',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-timestamp'], name='autopsy_mar_symbol_4c7e61_idx'), models.Index(fields=['regime', '-timestamp'], name='autopsy_mar_regime_576e9f_idx'), models.Index(fields=['session', '-timestamp'], name='autopsy_mar_session_d4e882_idx'), models.Index(fields=['-insight_index'], name='autopsy_mar_insight_ad0c8f_idx'), models.Index(fields=['vocabulary_hash'], name='autopsy_mar_vocabul_6852c6_idx')],
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='InsightTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('structure', models.TextField(help_text="e.g., 'Price is {action} as {condition}.'")),
                ('slots', models.JSONField(default=list, help_text="['action', 'condition'] - vocabulary categories")),
                ('regime_filter', models.JSONField(blank=True, default=list, help_text='Only use for these regimes')),
                ('structure_filter', models.JSONField(blank=True, default=list, help_text='Only use for these structures')),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insight Template',
                'verbose_name_plural': 'Insight Templates',
                'db_table': 'autopsy_insighttemplate',
                'ordering': ['-priority', 'usage_count'],
                'indexes': [models.Index(fields=['is_active', '-priority'], name='autopsy_ins_is_acti_8ef2fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='VariationVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, help_text='liquidity | momentum | structure | regime | session | volume', max_length=50)),
                ('subcategory', models.CharField(blank=True, help_text='building | forming | sweeping | etc.', max_length=50)),
                ('base_phrase', models.CharField(help_text='Original/canonical phrase', max_length=200)),
                ('variations', models.JSONField(default=list, help_text='Array of alternative phrasings')),
                ('usage_count', models.IntegerField(default=0, help_text='How many times used')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('appropriate_for', models.JSONField(default=dict, help_text="{'regime': ['trending'], 'session': ['london'], ...}")),
                ('avoid_with', models.JSONField(default=list, help_text="Don't use with these other phrases")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=100, help_text='Higher = preferred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variation Vocabulary',
                'verbose_name_plural': 'Variation Vocabularies',
                'db_table': 'autopsy_variationvocabulary',
                'ordering': ['category', '-priority'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='autopsy_var_categor_768565_idx'), models.Index(fields=['-usage_count'], name='autopsy_var_usage_c_f7a2e3_idx')],
            },
        ),
    ]
