# Generated by Django 4.2.7 on 2025-11-09 03:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Rule set name (e.g., 'FTMO', 'MyFundedFX')", max_length=100, unique=True)),
                ('max_daily_loss_pct', models.FloatField(default=5.0, help_text='Maximum daily loss as percentage of account balance', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_daily_loss_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum daily loss in absolute currency amount (optional)', max_digits=20, null=True)),
                ('max_trades_per_day', models.IntegerField(default=10, help_text='Maximum number of trades allowed per day', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_open_positions', models.IntegerField(default=3, help_text='Maximum number of simultaneously open positions', validators=[django.core.validators.MinValueValidator(1)])),
                ('blackout_minutes', models.IntegerField(default=5, help_text='Minutes to wait between trades on the same symbol', validators=[django.core.validators.MinValueValidator(0)])),
                ('trading_start_time', models.TimeField(blank=True, help_text='Start of allowed trading hours (UTC)', null=True)),
                ('trading_end_time', models.TimeField(blank=True, help_text='End of allowed trading hours (UTC)', null=True)),
                ('max_position_size_pct', models.FloatField(default=2.0, help_text='Maximum position size as percentage of account', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_risk_per_trade_pct', models.FloatField(default=1.0, help_text='Maximum risk per trade as percentage of account', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('allowed_symbols', models.TextField(blank=True, help_text='Comma-separated list of allowed symbols (leave empty for all)')),
                ('blacklisted_symbols', models.TextField(blank=True, help_text='Comma-separated list of blacklisted symbols')),
                ('min_confidence_score', models.FloatField(default=60.0, help_text='Minimum confidence score required to take a trade', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('allow_weekend_trading', models.BooleanField(default=False, help_text='Allow trading on weekends')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule set is currently active')),
                ('account_balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Current account balance for percentage calculations', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prop Trading Rule',
                'verbose_name_plural': 'Prop Trading Rules',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('sl', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Stop Loss')),
                ('tp', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Take Profit')),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('strategy', models.CharField(max_length=50)),
                ('regime', models.CharField(choices=[('Trend', 'Trend'), ('Breakout', 'Breakout'), ('MeanReversion', 'Mean Reversion'), ('Squeeze', 'Squeeze')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_allowed', models.BooleanField(default=True, help_text='Whether signal passed prop rules validation')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for signal rejection')),
                ('prop_rule_checked', models.ForeignKey(blank=True, help_text='Prop rule set used for validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='signals.proprules')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this signal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Signal',
                'verbose_name_plural': 'Trading Signals',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at', 'symbol'], name='signals_sig_receive_ee79f5_idx'), models.Index(fields=['strategy', 'regime'], name='signals_sig_strateg_54e755_idx')],
            },
        ),
    ]
