# Generated by Django 4.2.7 on 2025-11-09 03:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(db_index=True, help_text="Name of the trading strategy (e.g., 'ZenithEdge-Trend')", max_length=100)),
                ('regime', models.CharField(blank=True, choices=[('Trend', 'Trend'), ('Breakout', 'Breakout'), ('MeanReversion', 'Mean Reversion'), ('Squeeze', 'Squeeze')], help_text='Specific regime if performance is regime-specific', max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, db_index=True, help_text='Specific symbol if performance is symbol-specific', max_length=20, null=True)),
                ('timeframe', models.CharField(blank=True, help_text='Specific timeframe if performance is timeframe-specific', max_length=10, null=True)),
                ('total_trades', models.IntegerField(default=0, help_text='Total number of completed trades', validators=[django.core.validators.MinValueValidator(0)])),
                ('winning_trades', models.IntegerField(default=0, help_text='Number of winning trades', validators=[django.core.validators.MinValueValidator(0)])),
                ('losing_trades', models.IntegerField(default=0, help_text='Number of losing trades', validators=[django.core.validators.MinValueValidator(0)])),
                ('win_rate', models.FloatField(default=0.0, help_text='Win rate as percentage (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('avg_rr', models.FloatField(default=0.0, help_text='Average risk-reward ratio achieved', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_rr', models.FloatField(default=0.0, help_text='Cumulative R-multiple (total R gained/lost)')),
                ('max_drawdown', models.FloatField(default=0.0, help_text='Maximum drawdown as percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('current_drawdown', models.FloatField(default=0.0, help_text='Current drawdown from peak', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, help_text='Total profit/loss in currency', max_digits=20)),
                ('avg_win', models.DecimalField(decimal_places=2, default=0, help_text='Average winning trade amount', max_digits=20)),
                ('avg_loss', models.DecimalField(decimal_places=2, default=0, help_text='Average losing trade amount', max_digits=20)),
                ('profit_factor', models.FloatField(default=0.0, help_text='Ratio of gross profit to gross loss', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('avg_confidence', models.FloatField(default=0.0, help_text='Average confidence score of signals', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('analysis_period_start', models.DateTimeField(blank=True, help_text='Start date of analysis period', null=True)),
                ('analysis_period_end', models.DateTimeField(blank=True, help_text='End date of analysis period', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time performance was calculated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this performance record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategy Performance',
                'verbose_name_plural': 'Strategy Performances',
                'ordering': ['-win_rate', '-total_trades'],
                'indexes': [models.Index(fields=['strategy_name', '-win_rate'], name='signals_str_strateg_b976fc_idx'), models.Index(fields=['regime', '-total_trades'], name='signals_str_regime_50ef9b_idx'), models.Index(fields=['-last_updated'], name='signals_str_last_up_24717f_idx')],
                'unique_together': {('strategy_name', 'regime', 'symbol', 'timeframe', 'user')},
            },
        ),
    ]
