# Generated by Django 4.2.7 on 2025-11-09 03:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0002_strategyperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='session',
            field=models.CharField(blank=True, choices=[('Asia', 'Asia Session'), ('London', 'London Session'), ('New York', 'New York Session')], db_index=True, help_text='FX trading session (auto-detected from timestamp)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SessionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('Asia', 'Asia Session'), ('London', 'London Session'), ('New York', 'New York Session')], db_index=True, help_text='FX trading session', max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='Weight multiplier for signals in this session (0.0-10.0, default 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('is_blocked', models.BooleanField(default=False, help_text='If true, signals during this session are auto-blocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this session rule')),
                ('user', models.ForeignKey(help_text='User who owns this session rule', on_delete=django.db.models.deletion.CASCADE, related_name='session_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Rule',
                'verbose_name_plural': 'Session Rules',
                'ordering': ['user', 'session'],
                'unique_together': {('user', 'session')},
            },
        ),
    ]
