# Generated by Django 4.2.7 on 2025-11-09 03:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0003_signal_session_sessionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='is_risk_blocked',
            field=models.BooleanField(default=False, help_text='Whether signal was blocked by risk control rules'),
        ),
        migrations.AddField(
            model_name='signal',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('loss', 'Loss')], default='pending', help_text='Trade outcome (pending until manually set or auto-detected)', max_length=10),
        ),
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_consecutive_losers', models.IntegerField(default=3, help_text='Maximum consecutive losing trades before auto-halt (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('max_daily_trades', models.IntegerField(default=10, help_text='Maximum total trades allowed per day (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_red_signals_per_day', models.IntegerField(default=5, help_text='Maximum rejected/blocked signals per day before halting (1-50)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether risk controls are currently active')),
                ('halt_until_reset', models.BooleanField(default=True, help_text='If true, halt trading until manual reset. If false, reset at midnight UTC.')),
                ('is_halted', models.BooleanField(default=False, help_text='Whether trading is currently halted due to risk violation')),
                ('halt_reason', models.TextField(blank=True, help_text='Reason for current halt (if any)')),
                ('halt_triggered_at', models.DateTimeField(blank=True, help_text='When the halt was triggered', null=True)),
                ('last_reset_at', models.DateTimeField(blank=True, help_text='When risk controls were last reset', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about risk control strategy')),
                ('user', models.ForeignKey(help_text='User who owns this risk control setting', on_delete=django.db.models.deletion.CASCADE, related_name='risk_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Control',
                'verbose_name_plural': 'Risk Controls',
                'ordering': ['user', '-is_active'],
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='risk_control_checked',
            field=models.ForeignKey(blank=True, help_text='Risk control setting used for validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='signals.riskcontrol'),
        ),
    ]
