# Generated by Django 4.2.7 on 2025-11-09 04:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0004_signal_is_risk_blocked_signal_outcome_riskcontrol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('took', 'Took the Trade'), ('skipped', 'Skipped the Trade'), ('partial', 'Partial Entry'), ('early_exit', 'Early Exit')], help_text='What decision did you make?', max_length=20)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Breakeven'), ('pending', 'Pending'), ('scratch', 'Scratch Trade')], default='pending', help_text='What was the result?', max_length=20)),
                ('pips', models.DecimalField(blank=True, decimal_places=2, help_text='Profit/loss in pips (positive for profit, negative for loss)', max_digits=10, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='How long was the trade open (in minutes)?', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Your thoughts, observations, and lessons learned')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(blank=True, help_text='Associated signal (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='signals.signal')),
                ('user', models.ForeignKey(help_text='User who created this journal entry', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade Journal Entry',
                'verbose_name_plural': 'Trade Journal Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='signals_tra_user_id_aa602b_idx'), models.Index(fields=['user', 'outcome'], name='signals_tra_user_id_2f8f31_idx'), models.Index(fields=['decision'], name='signals_tra_decisio_0dac77_idx')],
            },
        ),
    ]
