# Generated by Django 4.2.7 on 2025-11-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_tradejournalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='chart_snapshot',
            field=models.ImageField(blank=True, help_text='Chart snapshot image for trade replay', null=True, upload_to='chart_snapshots/'),
        ),
        migrations.AddField(
            model_name='signal',
            name='entry_bar_index',
            field=models.IntegerField(blank=True, help_text='Bar index where signal was generated', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='exit_bar_index',
            field=models.IntegerField(blank=True, help_text='Bar index where trade was closed (SL/TP hit)', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='exit_reason',
            field=models.CharField(choices=[('tp_hit', 'Take Profit Hit'), ('sl_hit', 'Stop Loss Hit'), ('manual', 'Manual Close'), ('active', 'Still Active')], default='active', help_text='Reason for trade exit', max_length=20),
        ),
        migrations.AddField(
            model_name='signal',
            name='replay_data',
            field=models.JSONField(blank=True, help_text='OHLCV data for replay (JSON format)', null=True),
        ),
    ]
