# Generated by Django 4.2.7 on 2025-11-09 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0006_signal_chart_snapshot_signal_entry_bar_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropChallengeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(choices=[('funding_pips', 'Funding Pips'), ('ftmo', 'FTMO'), ('myforexfunds', 'MyForexFunds'), ('the5ers', 'The5%ers'), ('topstep', 'TopStep'), ('custom', 'Custom')], default='ftmo', max_length=50)),
                ('account_size', models.IntegerField(default=10000, help_text='Challenge account size in USD')),
                ('max_daily_loss_pct', models.DecimalField(decimal_places=2, default=5.0, help_text='Max daily loss as % of account (e.g., 5.00 = 5%)', max_digits=5)),
                ('max_overall_loss_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Max overall drawdown as % of account (e.g., 10.00 = 10%)', max_digits=5)),
                ('min_trading_days', models.IntegerField(default=5, help_text='Minimum number of trading days required')),
                ('profit_target_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Profit target as % of account to pass (e.g., 10.00 = 10%)', max_digits=5)),
                ('news_blackout_minutes', models.IntegerField(default=2, help_text='Minutes before/after major news to block trading')),
                ('leverage', models.IntegerField(default=100, help_text='Maximum leverage allowed (e.g., 100 = 100:1)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this challenge currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prop Challenge Config',
                'verbose_name_plural': 'Prop Challenge Configs',
                'db_table': 'signals_propchallengeconfig',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Total profit/loss in USD', max_digits=10)),
                ('daily_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text="Today's profit/loss in USD", max_digits=10)),
                ('peak_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Highest balance reached', max_digits=10)),
                ('trading_days', models.IntegerField(default=0, help_text='Number of days traded')),
                ('total_trades', models.IntegerField(default=0, help_text='Total number of trades')),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('daily_loss_violations', models.IntegerField(default=0, help_text='Times daily loss limit was hit')),
                ('overall_loss_violations', models.IntegerField(default=0, help_text='Times overall loss limit was hit')),
                ('news_blackout_violations', models.IntegerField(default=0, help_text='Trades during news blackout')),
                ('status', models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('failed', 'Failed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_trade_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='signals.propchallengeconfig')),
            ],
            options={
                'verbose_name': 'Prop Challenge Progress',
                'verbose_name_plural': 'Prop Challenge Progress',
                'db_table': 'signals_propchallengeprogress',
            },
        ),
    ]
