# Generated by Django 4.2.7 on 2025-11-09 11:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_propchallengeconfig_propchallengeprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Version identifier (e.g., 'v1.0', 'v2.1-optimized')", max_length=20, unique=True)),
                ('weights', models.JSONField(default=dict, help_text='Weights dict: {signal_confidence: 0.32, atr_safety: 0.18, ...}')),
                ('min_score_threshold', models.IntegerField(default=60, help_text='Minimum acceptable score (used as dashboard default filter)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=False, help_text='Only one version should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Change notes or reasoning for this weight configuration')),
            ],
            options={
                'verbose_name': 'Scoring Weights',
                'verbose_name_plural': 'Scoring Weights',
                'db_table': 'scoring_weights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeScore',
            fields=[
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_score', serialize=False, to='signals.signal')),
                ('ai_score', models.IntegerField(db_index=True, help_text='AI-computed score (0-100, higher is better)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_breakdown', models.JSONField(default=list, help_text='List of dicts: [{factor, raw_value, weight, contribution, explanation}]')),
                ('version', models.CharField(help_text='ScoringWeights version used to compute this score', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_factor', models.FloatField(default=0.0, help_text='Normalized confidence 0-1')),
                ('atr_safety_factor', models.FloatField(default=0.0, help_text='ATR safety score 0-1')),
                ('strategy_bias_factor', models.FloatField(default=0.0, help_text='Strategy bias 0-1')),
                ('regime_fit_factor', models.FloatField(default=0.0, help_text='Regime fit score 0-1')),
                ('rolling_win_rate', models.FloatField(default=0.0, help_text='Rolling win rate 0-1')),
            ],
            options={
                'verbose_name': 'AI Trade Score',
                'verbose_name_plural': 'AI Trade Scores',
                'db_table': 'trade_score',
                'ordering': ['-ai_score', '-created_at'],
                'indexes': [models.Index(fields=['-ai_score', '-created_at'], name='trade_score_ai_scor_73cfb8_idx'), models.Index(fields=['version'], name='trade_score_version_34e6a2_idx')],
            },
        ),
    ]
