# Generated by Django 4.2.7 on 2025-11-09 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0008_scoringweights_tradescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for webhook URL', unique=True)),
                ('webhook_url', models.CharField(blank=True, help_text='Full webhook URL with UUID', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable webhook')),
                ('signal_count', models.IntegerField(default=0, help_text='Total signals received via this webhook')),
                ('last_signal_at', models.DateTimeField(blank=True, help_text='Timestamp of last received signal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Configuration',
                'verbose_name_plural': 'Webhook Configurations',
                'db_table': 'webhook_config',
                'ordering': ['-created_at'],
            },
        ),
    ]
