# Generated by Django 4.2.7 on 2025-11-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0009_webhookconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False, help_text='Whether signal passed all validation checks')),
                ('blocked_reason', models.CharField(choices=[('passed', 'Passed All Checks'), ('news', 'News Blackout'), ('prop', 'Prop Challenge Violation'), ('score', 'Low AI Score'), ('strategy', 'Strategy Not Allowed'), ('manual', 'Manual Block'), ('multiple', 'Multiple Issues')], default='passed', help_text='Reason for blocking (if blocked)', max_length=20)),
                ('final_ai_score', models.IntegerField(blank=True, help_text='Final AI score from TradeScorer (0-100)', null=True)),
                ('news_check', models.BooleanField(default=True, help_text='Passed news blackout check')),
                ('prop_check', models.BooleanField(default=True, help_text='Passed prop challenge rules check')),
                ('score_check', models.BooleanField(default=True, help_text='Passed minimum AI score check')),
                ('strategy_check', models.BooleanField(default=True, help_text='Passed strategy match check')),
                ('evaluation_notes', models.TextField(blank=True, help_text='Detailed evaluation notes/reasons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.OneToOneField(help_text='Signal being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='signals.signal')),
            ],
            options={
                'verbose_name': 'Signal Evaluation',
                'verbose_name_plural': 'Signal Evaluations',
                'db_table': 'signal_evaluation',
                'ordering': ['-created_at'],
            },
        ),
    ]
