# Generated by Django 4.2.7 on 2025-11-09 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0010_signalevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalevaluation',
            name='is_overridden',
            field=models.BooleanField(default=False, help_text='Whether this evaluation was manually overridden by admin'),
        ),
        migrations.AddField(
            model_name='signalevaluation',
            name='overridden_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of override', null=True),
        ),
        migrations.AddField(
            model_name='signalevaluation',
            name='overridden_by',
            field=models.ForeignKey(blank=True, help_text='Admin who performed the override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SignalOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_reason', models.CharField(help_text='Original blocked reason before override', max_length=20)),
                ('new_reason', models.CharField(default='manual-override', help_text='New reason after override', max_length=20)),
                ('override_reason', models.TextField(blank=True, help_text="Admin's explanation for the override")),
                ('override_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(help_text='Admin who performed the override', on_delete=django.db.models.deletion.CASCADE, related_name='signal_overrides', to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(help_text='Signal that was overridden', on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to='signals.signal')),
            ],
            options={
                'verbose_name': 'Signal Override Log',
                'verbose_name_plural': 'Signal Override Logs',
                'db_table': 'signal_override_log',
                'ordering': ['-override_at'],
            },
        ),
    ]
