# Generated by Django 4.2.7 on 2025-11-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0011_signalevaluation_is_overridden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookconfig',
            name='hmac_secret',
            field=models.CharField(blank=True, help_text='Optional HMAC secret for signature validation', max_length=255),
        ),
    ]
