# Generated by Django 4.2.7 on 2025-11-11 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_webhookconfig_hmac_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='Month for this aggregation (YYYY-MM-01)')),
                ('strategy_name', models.CharField(blank=True, help_text='Strategy name (blank for all strategies)', max_length=50)),
                ('symbol', models.CharField(blank=True, help_text='Trading symbol (blank for all symbols)', max_length=20)),
                ('total_signals', models.IntegerField(default=0, help_text='Total signals validated this period')),
                ('approved_count', models.IntegerField(default=0, help_text='Number of approved signals (≥80)')),
                ('conditional_count', models.IntegerField(default=0, help_text='Number of conditional signals (60-79)')),
                ('rejected_count', models.IntegerField(default=0, help_text='Number of rejected signals (<60)')),
                ('avg_truth_index', models.DecimalField(decimal_places=2, default=0, help_text='Average truth index for this period', max_digits=5)),
                ('avg_technical_score', models.DecimalField(decimal_places=2, default=0, help_text='Average technical integrity score', max_digits=5)),
                ('avg_sentiment_score', models.DecimalField(decimal_places=2, default=0, help_text='Average sentiment coherence score', max_digits=5)),
                ('validated_outcomes', models.IntegerField(default=0, help_text='Number of signals with known outcomes')),
                ('correct_predictions', models.IntegerField(default=0, help_text='Number of correct predictions')),
                ('accuracy_rate', models.DecimalField(decimal_places=2, default=0, help_text='Prediction accuracy percentage', max_digits=5)),
                ('false_positives', models.IntegerField(default=0, help_text='Approved signals that failed (SL hit)')),
                ('false_negatives', models.IntegerField(default=0, help_text='Rejected signals that would have succeeded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Validation Score',
                'verbose_name_plural': 'Validation Scores',
                'db_table': 'validation_score',
                'ordering': ['-period_month', 'strategy_name'],
                'indexes': [models.Index(fields=['-period_month'], name='validation__period__8f9c83_idx'), models.Index(fields=['strategy_name'], name='validation__strateg_9e7a7f_idx'), models.Index(fields=['-accuracy_rate'], name='validation__accurac_bfb27f_idx')],
                'unique_together': {('period_month', 'strategy_name', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='TradeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truth_index', models.DecimalField(decimal_places=2, help_text='AI-calculated truth score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('approved', 'Approved (≥80)'), ('conditional', 'Conditional (60-79)'), ('rejected', 'Rejected (<60)')], default='rejected', help_text='Validation decision', max_length=20)),
                ('breakdown', models.JSONField(default=dict, help_text='Sub-scores for each validation criterion (technical, volatility, regime, sentiment, historical, psychological)')),
                ('validation_notes', models.JSONField(default=list, help_text='List of validation check results and warnings')),
                ('context_summary', models.TextField(blank=True, help_text='AI-generated narrative explaining the signal with context')),
                ('recommendation', models.TextField(blank=True, help_text='AI recommendation for trader action')),
                ('accuracy_history', models.JSONField(default=dict, help_text='Historical accuracy data for reputation scoring')),
                ('validated_at', models.DateTimeField(auto_now_add=True, help_text='When validation was performed')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('signal', models.OneToOneField(help_text='Associated signal being validated', on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='signals.signal')),
            ],
            options={
                'verbose_name': 'Trade Validation',
                'verbose_name_plural': 'Trade Validations',
                'db_table': 'trade_validation',
                'ordering': ['-validated_at'],
                'indexes': [models.Index(fields=['-truth_index'], name='trade_valid_truth_i_19fa5c_idx'), models.Index(fields=['status'], name='trade_valid_status_60bded_idx'), models.Index(fields=['-validated_at'], name='trade_valid_validat_ad13b4_idx')],
            },
        ),
    ]
