# Generated by Django 4.2.7 on 2025-11-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0015_tradevalidation_quality_metrics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketinsight',
            new_name='signals_mar_receive_ff78a5_idx',
            old_name='signals_mar_receive_idx',
        ),
        migrations.RenameIndex(
            model_name='marketinsight',
            new_name='signals_mar_strateg_85fe63_idx',
            old_name='signals_mar_strateg_idx',
        ),
        migrations.RenameIndex(
            model_name='marketinsight',
            new_name='signals_mar_bias_0f179e_idx',
            old_name='signals_mar_bias_mk_idx',
        ),
    ]
