# Generated by Django 4.2.7 on 2025-11-12 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0016_rename_signals_mar_receive_idx_signals_mar_receive_ff78a5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Notification title (e.g., 'New Insight – EURUSD (1H)')", max_length=120)),
                ('snippet', models.TextField(help_text='Short narrative summary (1-2 lines)')),
                ('confidence', models.FloatField(help_text='AI confidence score (0-100)')),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', help_text='Notification priority level', max_length=10)),
                ('news_headline', models.CharField(blank=True, help_text='Optional news headline reference', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification was created')),
                ('read', models.BooleanField(default=False, help_text='Whether user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('delivered', models.BooleanField(default=False, help_text='Whether notification was successfully delivered via WebSocket')),
                ('signal', models.ForeignKey(help_text='Signal/Insight this notification is about', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='signals.signal')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='insight_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_enabled', models.BooleanField(default=True, help_text='Enable in-app web notifications')),
                ('push_enabled', models.BooleanField(default=False, help_text='Enable browser push notifications')),
                ('email_digest_enabled', models.BooleanField(default=False, help_text='Enable daily email digest')),
                ('min_confidence', models.IntegerField(default=65, help_text='Minimum confidence threshold for notifications (0-100)')),
                ('strategies_filter', models.JSONField(blank=True, default=list, help_text='List of strategies to receive notifications for (empty = all)')),
                ('symbols_filter', models.JSONField(blank=True, default=list, help_text='List of symbols to receive notifications for (empty = all)')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable quiet hours (no notifications during specified time)')),
                ('quiet_start_time', models.TimeField(blank=True, help_text='Quiet hours start time (e.g., 22:00)', null=True)),
                ('quiet_end_time', models.TimeField(blank=True, help_text='Quiet hours end time (e.g., 08:00)', null=True)),
                ('high_priority_only', models.BooleanField(default=False, help_text='Only receive high priority notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='Delivery channel (websocket, push, email)', max_length=20)),
                ('success', models.BooleanField(default=True, help_text='Whether delivery was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed', null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.insightnotification')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='insightnotification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_1a4132_idx'),
        ),
        migrations.AddIndex(
            model_name='insightnotification',
            index=models.Index(fields=['user', 'read'], name='notificatio_user_id_1cc280_idx'),
        ),
    ]
